services:
  instachef:
    build:
      context: .
      dockerfile: Dockerfile
    image: instachef:latest
    restart: unless-stopped
    network_mode: "service:vpn" 
    depends_on:
      - vpn
    env_file:
      - .env
    environment:
      INSTACHEF_MODE: ${INSTACHEF_MODE:-telegram}
    command: uv run main.py --mode ${INSTACHEF_MODE:-telegram}
    volumes:
      - ./db:/app/db
      - ./downloaded_reels:/app/downloaded_reels
    stdin_open: true
    tty: true

  vpn:
    image: linuxserver/wireguard:latest
    container_name: vpn_gateway
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    devices:
      - /dev/net/tun:/dev/net/tun
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - WIREGUARD_CONF_64=${WIREGUARD_CONF_64} 
    entrypoint: >
      sh -c "echo \"$$WIREGUARD_CONF_64\" | base64 -d > /config/wg0.conf && exec /init"
    restart: unless-stopped